In [1]:
import numpy as np

In [2]:
a = np.arange(25).reshape(5,5)

In [3]:
a[-2:,-2:]

array([[18, 19],
       [23, 24]])

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [5]:
a[[-2,-1],[-2,-1]]

array([18, 24])

In [7]:
a[[-2,-1]]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
a[[-2,-1]][:,-2:]

array([[18, 19],
       [23, 24]])

In [14]:
a[[True,False,True,False,True]] #마스킹 기법 : True만 가져옴

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [15]:
a[np.ix_([0,2,4],[0,2])]

array([[ 0,  2],
       [10, 12],
       [20, 22]])

In [18]:
a[(0,1),(2,1)]

array([2, 6])

In [19]:
a[[True,True,True,True,True]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
a[True,True,True,True,True]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [21]:
from collections import namedtuple

In [22]:
namedtuple('Moon','name')

__main__.Moon

In [25]:
t = namedtuple('AttendanceSheet',['name','attendane'])

In [29]:
x = t('moon','yes')

In [30]:
x[0]

'moon'

In [31]:
x.name

'moon'

In [33]:
a = np.arange(10)

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
a= np.array([1,2,3])

In [37]:
a.shape

(3,)

In [38]:
np.sqrt(4)

2.0

In [42]:
np.sqrt((4,9))

array([2., 3.])

In [41]:
import math

In [43]:
math.sqrt([4,9])

TypeError: must be real number, not list

In [44]:
np.add([1,2,],[4,5])

array([5, 7])

In [48]:
x = np.array([2,2,])

In [52]:
np.dot(x,x)

8

In [53]:
x.dot(x)

8

In [54]:
type(np.dot)

builtin_function_or_method

In [55]:
np.abs([-3,-1])

array([3, 1])

----

In [56]:
a = [1,2,3]

In [57]:
b = a

In [58]:
b.append(4)

In [59]:
a

[1, 2, 3, 4]

In [60]:
b = a.copy()

In [62]:
b.append(5)

In [63]:
a

[1, 2, 3, 4]

In [69]:
a = [[1,2,3]]

In [65]:
b = a

In [70]:
b = a.copy()

In [71]:
a[0][1] = 4

In [72]:
b

[[1, 4, 3]]

겹겹이 쌓여 있을 때, copy를 해도 값이 바뀜 => 안에것 까지 copy가 되지 않는다!

스왈로우 카피 : 얕게만 카피하는것

In [74]:
import copy

In [75]:
a = [[1,2,3]]

In [76]:
b = copy.deepcopy(a)

In [77]:
a[0][1]=4

In [78]:
b

[[1, 2, 3]]

In [83]:
a = np.array([1,2,3])

In [84]:
b = a.copy()

In [85]:
a[0] = 4

In [86]:
b

array([1, 2, 3])

In [87]:
a = np.array([[1,2,3],[4,5,6]])

In [88]:
b = a.copy()

In [89]:
a[0][0] = 4

In [90]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a = np.arange(10).reshape(2,5)

In [97]:
b = a.ravel() #view

In [96]:
a.flatten() #copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
b[0] = 3

In [99]:
a

array([[3, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
a.T

array([[3, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [102]:
np.newaxis

In [106]:
a[:,np.newaxis] # 차원을 변경시킴

array([[[3, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [108]:
a[:,np.newaxis].shape

(2, 1, 5)

In [109]:
a[:,:,np.newaxis].shape

(2, 5, 1)

In [110]:
a[:,np.newaxis].shape

(2, 1, 5)

In [117]:
# from pprint import pprint

In [118]:
a = [[1,2],[3,4]]

In [119]:
a

[[1, 2], [3, 4]]

In [120]:
a = [[[1,2],[3,4],],[[1,2],[3,4]]]

In [122]:
a

[[[1, 2], [3, 4]], [[1, 2], [3, 4]]]

In [123]:
a = [[1,2],[3,4]]

In [124]:
b = np.array(a)

In [126]:
b[:,:,np.newaxis]

array([[[1],
        [2]],

       [[3],
        [4]]])

In [127]:
c = b[::,np.newaxis].copy()

In [128]:
c

array([[[1, 2]],

       [[3, 4]]])

In [129]:
c[0]

array([[1, 2]])

In [130]:
c[1]

array([[3, 4]])

In [132]:
a = np.arange(10)

In [133]:
a.itemsize

8

In [134]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])