In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [5]:
a[np.newaxis]

array([[1, 2, 3]])

In [6]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [7]:
a = np.array([[1,2,3],[4,5,6]])

In [8]:
a[np.newaxis]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [9]:
a[:,:,np.newaxis]

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [10]:
a = np.array([[1,2,3],[4,5,6]])

In [11]:
a[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [12]:
a = np.array([1,2,3])

In [15]:
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [16]:
np.tile(a,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [18]:
np.tile(a,[2,3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [20]:
%%writefile t.csv
1,2,3
4,5,6

Writing t.csv


In [23]:
x = np.loadtxt('t.csv',delimiter=',')

In [24]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
x = np.genfromtxt('t.csv',delimiter=',')

In [29]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [33]:
y = np.fromfile('t.csv',sep=',')

In [34]:
y

array([1., 2., 3.])

In [37]:
x = np.array([[1,2],[4,3]])

In [38]:
x

array([[1, 2],
       [4, 3]])

In [41]:
np.savez('tt',x)

In [42]:
s = np.load('tt.npz')

In [43]:
%%writefile moon.txt
sdf ffsdf
sadasdasd
fasdfsadfsdgwggf
asfaSdasd

Writing moon.txt


In [62]:
file = open('moon.txt')

In [47]:
file.readline()

'sdf ffsdf\n'

In [54]:
file = open('moon.txt','rb')

In [49]:
type(file)

_io.BufferedReader

In [50]:
file.readline()

b'sdf ffsdf\n'

In [51]:
file.readlines()

[b'sadasdasd\n', b'fasdfsadfsdgwggf\n', b'asfaSdasd\n']

In [52]:
file.readline()

b''

In [55]:
next(file)

b'sdf ffsdf\n'

In [56]:
a = range(10)

In [57]:
b = iter(a)

In [60]:
next(b)

2

In [63]:
file.write('Hello , World!')

UnsupportedOperation: not writable

In [66]:
file = open('moon2.txt',mode = 'w')

In [68]:
file.write('Hello,World!')
file.close()

In [71]:
file2 = open('moon2.txt')

In [72]:
dir(open)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [73]:
dir(file2)

['_CHUNK_SIZE',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_checkClosed',
 '_checkReadable',
 '_checkSeekable',
 '_checkWritable',
 '_finalizing',
 'buffer',
 'close',
 'closed',
 'detach',
 'encoding',
 'errors',
 'fileno',
 'flush',
 'isatty',
 'line_buffering',
 'mode',
 'name',
 'newlines',
 'read',
 'readable',
 'readline',
 'readlines',
 'reconfigure',
 'seek',
 'seekable',
 'tell',
 'truncate',
 'writable',
 'write',
 'write_through',
 'writelines']

In [75]:
import pickle #python3  버전이 다르면 적용이 안 될 수도 있다!!

In [78]:
np.save('tttt',x)

In [79]:
s = np.load('tttt.npy')

In [80]:
s

array([[1, 2],
       [4, 3]])

In [81]:
with open('sun.ss','wb') as f:
    pickle.dump(s,f)

In [82]:
with open('sun.ss','rb') as f:
    ss = pickle.load(f)

In [83]:
ss

array([[1, 2],
       [4, 3]])

In [86]:
a = [1,2,3]

In [87]:
b = a[:]

In [88]:
b[2] = 0

In [91]:
b #copy

[1, 2, 0]

In [90]:
a

[1, 2, 3]