In [10]:
import numpy as np
import pandas as pd
import seaborn as sns

In [4]:
a = np.arange(30).reshape(5,6)

In [5]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [8]:
a[[1,2]][:,2:4]

array([[ 8,  9],
       [14, 15]])

In [15]:
data = pd.read_csv('data/billboard.csv', engine = 'python')

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317 entries, 0 to 316
Data columns (total 83 columns):
year               317 non-null int64
artist.inverted    317 non-null object
track              317 non-null object
time               317 non-null object
genre              317 non-null object
date.entered       317 non-null object
date.peaked        317 non-null object
x1st.week          317 non-null int64
x2nd.week          312 non-null float64
x3rd.week          307 non-null float64
x4th.week          300 non-null float64
x5th.week          292 non-null float64
x6th.week          280 non-null float64
x7th.week          269 non-null float64
x8th.week          260 non-null float64
x9th.week          253 non-null float64
x10th.week         244 non-null float64
x11th.week         236 non-null float64
x12th.week         222 non-null float64
x13th.week         210 non-null float64
x14th.week         204 non-null float64
x15th.week         197 non-null float64
x16th.week         182 no

In [17]:
data

year      artist.inverted  \
0    2000      Destiny's Child   
1    2000              Santana   
2    2000        Savage Garden   
3    2000              Madonna   
4    2000  Aguilera, Christina   
5    2000                Janet   
6    2000      Destiny's Child   
7    2000    Iglesias, Enrique   
8    2000                Sisqo   
9    2000             Lonestar   
10   2000               N'Sync   
11   2000  Aguilera, Christina   
12   2000     Vertical Horizon   
13   2000                Creed   
14   2000              Aaliyah   
15   2000      matchbox twenty   
16   2000        Carey, Mariah   
17   2000          Hill, Faith   
18   2000                  Mya   
19   2000                Dream   
20   2000        Braxton, Toni   
21   2000        Anthony, Marc   
22   2000                  98�   
23   2000      Destiny's Child   
24   2000         3 Doors Down   
25   2000                Sisqo   
26   2000  Aguilera, Christina   
27   2000     Houston, Whitney   
28   2000                  Joe   
29   2000      Jordan, Montell   
..    ...                  ...   
287  2000              2Ge+her   
288  2000       Madison Avenue   
289  2000                  Eve   
290  2000          Limp Bizkit   
291  2000      Spencer, Tracie   
292  2000            Nu Flavor   
293  2000                Tamar   
294  2000       Levert, Gerald   
295  2000           Hart, Beth   
296  2000          Diffie, Joe   
297  2000      Funkmaster Flex   
298  2000         Price, Kelly   
299  2000             En Vogue   
300  2000          Herndon, Ty   
301  2000            Anastacia   
302  2000                Trina   
303  2000              Lil' Mo   
304  2000              A*Teens   
305  2000        Sheist, Shade   
306  2000           De La Soul   
307  2000       Larrieux, Amel   
308  2000        Braxton, Toni   
309  2000              Tuesday   
310  2000            LL Cool J   
311  2000             Master P   
312  2000     Ghostface Killah   
313  2000          Smith, Will   
314  2000        Zombie Nation   
315  2000       Eastsidaz, The   
316  2000               Fragma   

                                                 track  time        genre  \
0                             Independent Women Part I  3:38         Rock   
1                                         Maria, Maria  4:18         Rock   
2                                   I Knew I Loved You  4:07         Rock   
3                                                Music  3:45         Rock   
4                Come On Over Baby (All I Want Is You)  3:38         Rock   
5                                Doesn't Really Matter  4:17         Rock   
6                                          Say My Name  4:31         Rock   
7                                          Be With You  3:36        Latin   
8                                           Incomplete  3:52         Rock   
9                                               Amazed  4:25      Country   
10                                    It's Gonna Be Me  3:10         Rock   
11                                   What A Girl Wants  3:18         Rock   
12                                 Everything You Want  4:01         Rock   
13                                 With Arms Wide Open  3:52         Rock   
14                                           Try Again  4:03         Rock   
15                                                Bent  4:12         Rock   
16                               Thank God I Found You  4:14         Rock   
17                                             Breathe  4:04          Rap   
18                   Case Of The Ex (Whatcha Gonna Do)  3:50         Rock   
19                                      He Loves U Not  3:43         Rock   
20                                He Wasn't Man Enough  4:21         Rock   
21                                      You Sang To Me  3:50        Latin   
22                  Give Me Just One Night (Una Noche)  3:24         Rock   
23                                     Jumpin' J

In [21]:
data.index[3]

3

In [20]:
range(0,10)[3]

3

In [25]:
data.melt(data.columns[:7]).set_index('year').loc[2000]

artist.inverted                                              track  \
year                                                                           
2000      Destiny's Child                           Independent Women Part I   
2000              Santana                                       Maria, Maria   
2000        Savage Garden                                 I Knew I Loved You   
2000              Madonna                                              Music   
2000  Aguilera, Christina              Come On Over Baby (All I Want Is You)   
2000                Janet                              Doesn't Really Matter   
2000      Destiny's Child                                        Say My Name   
2000    Iglesias, Enrique                                        Be With You   
2000                Sisqo                                         Incomplete   
2000             Lonestar                                             Amazed   
2000               N'Sync                                   It's Gonna Be Me   
2000  Aguilera, Christina                                  What A Girl Wants   
2000     Vertical Horizon                                Everything You Want   
2000                Creed                                With Arms Wide Open   
2000              Aaliyah                                          Try Again   
2000      matchbox twenty                                               Bent   
2000        Carey, Mariah                              Thank God I Found You   
2000          Hill, Faith                                            Breathe   
2000                  Mya                  Case Of The Ex (Whatcha Gonna Do)   
2000                Dream                                     He Loves U Not   
2000        Braxton, Toni                               He Wasn't Man Enough   
2000        Anthony, Marc                                     You Sang To Me   
2000                  98�                 Give Me Just One Night (Una Noche)   
2000      Destiny's Child                                    Jumpin' Jumpin'   
2000         3 Doors Down                                         Kryptonite   
2000                Sisqo                                         Thong Song   
2000  Aguilera, Christina                                      I Turn To You   
2000     Houston, Whitney                               My Love Is Your Love   
2000                  Joe                                       I Wanna Know   
2000      Jordan, Montell                                 Get It On.. Tonite   
...                   ...                                                ...   
2000              2Ge+her  The Hardest Part Of Breaking Up (Is Getting Ba...   
2000       Madison Avenue                                 Don't Call Me Baby   
2000                  Eve                                         Got It All   
2000          Limp Bizkit                                        Re-Arranged   
2000      Spencer, Tracie                                  Still In My Heart   
2000            Nu Flavor                                     3 Little Words   
2000                Tamar                         If You Don't Wanna Love Me   
2000       Levert, Gerald                                         Baby U Are   
2000           Hart, Beth                                          L.A. Song   
2000          Diffie, Joe                                  The Quittin' Kind   
2000      Funkmaster Flex                                             Do You   
2000         Price, Kelly                                 Love Sets You Free   
2000             En Vogue                                             Riddle   
2000          Herndon, Ty                                           No Mercy   
2000            Anastacia                                     I'm Outta Love   
2000                Trina                                          Pull Over   
2000              Lil' Mo                                              Ta Da   
2000      

In [26]:
a = {1,2,3}

In [27]:
b = {3,4}

In [28]:
a.intersection(b)

{3}

In [30]:
a.intersection([3,4])

{3}

In [35]:
a = np.arange(10)

In [36]:
a>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [39]:
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [40]:
3 or []

3

In [45]:
a[(a>3) | (a<9)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
class X(int):
    def __add__(self,other):
        print('안더해')

In [47]:
X(3) + X(5)

안더해


In [48]:
1 in [1,2,3]

True

In [50]:
1 in '123'

TypeError: 'in <string>' requires string as left operand, not int

In [52]:
'1' in '123'

True

In [53]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.where(a>4,1,0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [59]:
np.where(a ==4)

(array([4]),)

In [60]:
x = [2,3,4]

In [62]:
x.index(2)

0

In [64]:
tips = sns.load_dataset('tips')

In [65]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
5         25.29  4.71    Male     No   Sun  Dinner     4
6          8.77  2.00    Male     No   Sun  Dinner     2
7         26.88  3.12    Male     No   Sun  Dinner     4
8         15.04  1.96    Male     No   Sun  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
11        35.26  5.00  Female     No   Sun  Dinner     4
12        15.42  1.57    Male     No   Sun  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
15        21.58  3.92    Male     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
17        16.29  3.71    Male     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
19        20.65  3.35    Male     No   Sat  Dinner     3
20        17.92  4.08    Male     No   Sat  Dinner     2
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
23        39.42  7.58    Male     No   Sat  Dinner     4
24        19.82  3.18    Male     No   Sat  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
26        13.37  2.00    Male     No   Sat  Dinner     2
27        12.69  2.00    Male     No   Sat  Dinner     2
28        21.70  4.30    Male     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
..          ...   ...     ...    ...   ...     ...   ...
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
217       11.59  1.50    Male    Yes   Sat  Dinner     2
218        7.74  1.44    Male    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
220       12.16  2.20    Male    Yes   Fri   Lunch     2
221       13.42  3.48  Female    Yes   Fri   Lunch     2
222        8.58  1.92    Male    Yes   Fri   Lunch     1
223       15.98  3.00  Female     No   Fri   Lunch     3
224       13.42  1.58    Male    Yes   Fri   Lunch     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
227       20.45  3.00    Male     No   Sat  Dinner     4
228       13.28  2.72    Male     No   Sat  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [66]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB


In [68]:
tips.time.astype('object')

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
5      Dinner
6      Dinner
7      Dinner
8      Dinner
9      Dinner
10     Dinner
11     Dinner
12     Dinner
13     Dinner
14     Dinner
15     Dinner
16     Dinner
17     Dinner
18     Dinner
19     Dinner
20     Dinner
21     Dinner
22     Dinner
23     Dinner
24     Dinner
25     Dinner
26     Dinner
27     Dinner
28     Dinner
29     Dinner
        ...  
214    Dinner
215    Dinner
216    Dinner
217    Dinner
218    Dinner
219    Dinner
220     Lunch
221     Lunch
222     Lunch
223     Lunch
224     Lunch
225     Lunch
226     Lunch
227    Dinner
228    Dinner
229    Dinner
230    Dinner
231    Dinner
232    Dinner
233    Dinner
234    Dinner
235    Dinner
236    Dinner
237    Dinner
238    Dinner
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: object

In [69]:
a = [1,2,3]

In [70]:
a[3] = 4

IndexError: list assignment index out of range

In [71]:
b = {'a':1}

In [72]:
b['x']

KeyError: 'x'

In [73]:
b['x'] = 2

In [74]:
b

{'a': 1, 'x': 2}

In [75]:
tips['time2'] = tips.time.astype('object')

In [76]:
tips.time2

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
5      Dinner
6      Dinner
7      Dinner
8      Dinner
9      Dinner
10     Dinner
11     Dinner
12     Dinner
13     Dinner
14     Dinner
15     Dinner
16     Dinner
17     Dinner
18     Dinner
19     Dinner
20     Dinner
21     Dinner
22     Dinner
23     Dinner
24     Dinner
25     Dinner
26     Dinner
27     Dinner
28     Dinner
29     Dinner
        ...  
214    Dinner
215    Dinner
216    Dinner
217    Dinner
218    Dinner
219    Dinner
220     Lunch
221     Lunch
222     Lunch
223     Lunch
224     Lunch
225     Lunch
226     Lunch
227    Dinner
228    Dinner
229    Dinner
230    Dinner
231    Dinner
232    Dinner
233    Dinner
234    Dinner
235    Dinner
236    Dinner
237    Dinner
238    Dinner
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time2, Length: 244, dtype: object

In [77]:
x = tips.time2.str

In [80]:
tips['size'] = tips['size'].astype('category')

In [81]:
tips.describe()

total_bill         tip
count  244.000000  244.000000
mean    19.785943    2.998279
std      8.902412    1.383638
min      3.070000    1.000000
25%     13.347500    2.000000
50%     17.795000    2.900000
75%     24.127500    3.562500
max     50.810000   10.000000

In [82]:
a = 'moon'

In [83]:
dir(a)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [86]:
t = tips.time.str

In [87]:
for i in tips.time:
    print(i)

Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Dinner
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lunch
Lu

In [95]:
tips.time.map(lambda x:'dinner' if x=='Dinner' else 'lunch' if x== 'Lunch' else x)

0      dinner
1      dinner
2      dinner
3      dinner
4      dinner
5      dinner
6      dinner
7      dinner
8      dinner
9      dinner
10     dinner
11     dinner
12     dinner
13     dinner
14     dinner
15     dinner
16     dinner
17     dinner
18     dinner
19     dinner
20     dinner
21     dinner
22     dinner
23     dinner
24     dinner
25     dinner
26     dinner
27     dinner
28     dinner
29     dinner
        ...  
214    dinner
215    dinner
216    dinner
217    dinner
218    dinner
219    dinner
220     lunch
221     lunch
222     lunch
223     lunch
224     lunch
225     lunch
226     lunch
227    dinner
228    dinner
229    dinner
230    dinner
231    dinner
232    dinner
233    dinner
234    dinner
235    dinner
236    dinner
237    dinner
238    dinner
239    dinner
240    dinner
241    dinner
242    dinner
243    dinner
Name: time, Length: 244, dtype: category
Categories (2, object): [lunch, dinner]

In [96]:
tips.time.map(lambda x:x.upper())

0      DINNER
1      DINNER
2      DINNER
3      DINNER
4      DINNER
5      DINNER
6      DINNER
7      DINNER
8      DINNER
9      DINNER
10     DINNER
11     DINNER
12     DINNER
13     DINNER
14     DINNER
15     DINNER
16     DINNER
17     DINNER
18     DINNER
19     DINNER
20     DINNER
21     DINNER
22     DINNER
23     DINNER
24     DINNER
25     DINNER
26     DINNER
27     DINNER
28     DINNER
29     DINNER
        ...  
214    DINNER
215    DINNER
216    DINNER
217    DINNER
218    DINNER
219    DINNER
220     LUNCH
221     LUNCH
222     LUNCH
223     LUNCH
224     LUNCH
225     LUNCH
226     LUNCH
227    DINNER
228    DINNER
229    DINNER
230    DINNER
231    DINNER
232    DINNER
233    DINNER
234    DINNER
235    DINNER
236    DINNER
237    DINNER
238    DINNER
239    DINNER
240    DINNER
241    DINNER
242    DINNER
243    DINNER
Name: time, Length: 244, dtype: category
Categories (2, object): [LUNCH, DINNER]

In [97]:
tips.time.str.upper()

0      DINNER
1      DINNER
2      DINNER
3      DINNER
4      DINNER
5      DINNER
6      DINNER
7      DINNER
8      DINNER
9      DINNER
10     DINNER
11     DINNER
12     DINNER
13     DINNER
14     DINNER
15     DINNER
16     DINNER
17     DINNER
18     DINNER
19     DINNER
20     DINNER
21     DINNER
22     DINNER
23     DINNER
24     DINNER
25     DINNER
26     DINNER
27     DINNER
28     DINNER
29     DINNER
        ...  
214    DINNER
215    DINNER
216    DINNER
217    DINNER
218    DINNER
219    DINNER
220     LUNCH
221     LUNCH
222     LUNCH
223     LUNCH
224     LUNCH
225     LUNCH
226     LUNCH
227    DINNER
228    DINNER
229    DINNER
230    DINNER
231    DINNER
232    DINNER
233    DINNER
234    DINNER
235    DINNER
236    DINNER
237    DINNER
238    DINNER
239    DINNER
240    DINNER
241    DINNER
242    DINNER
243    DINNER
Name: time, Length: 244, dtype: object

In [98]:
a = 'moon beauty'

In [99]:
b = '/sun/moon.jpg'

In [100]:
a.split(' ')

['moon', 'beauty']

In [101]:
b.split('/')[-1]

'moon.jpg'

In [114]:
b.rsplit('/',1)

['/sun', 'moon.jpg']

In [115]:
b.split('/',1)

['', 'sun/moon.jpg']

In [118]:
'       as8'.strip() #공백 제거

'as8'

In [119]:
" sd sd g qwfqef   ".strip()

'sd sd g qwfqef'

In [120]:
b.replace('moon','sun')

'/sun/sun.jpg'

In [121]:
c = 'moon,moon,moon'

In [123]:
c.replace('moon','sun')

'sun,sun,sun'

In [124]:
b.replace('moon','sun').replace('sun','un')

'/un/un.jpg'

In [125]:
x = ['1','2','3']

In [126]:
''.join(x)

'123'

In [127]:
'-'.join(x)

'1-2-3'

In [129]:
list('123')

['1', '2', '3']

In [130]:
a = '1'

In [131]:
a.zfill(3)

'001'

In [132]:
tips.rename({'size':'size_'})

total_bill   tip     sex smoker   day    time size   time2
0         16.99  1.01  Female     No   Sun  Dinner    2  Dinner
1         10.34  1.66    Male     No   Sun  Dinner    3  Dinner
2         21.01  3.50    Male     No   Sun  Dinner    3  Dinner
3         23.68  3.31    Male     No   Sun  Dinner    2  Dinner
4         24.59  3.61  Female     No   Sun  Dinner    4  Dinner
5         25.29  4.71    Male     No   Sun  Dinner    4  Dinner
6          8.77  2.00    Male     No   Sun  Dinner    2  Dinner
7         26.88  3.12    Male     No   Sun  Dinner    4  Dinner
8         15.04  1.96    Male     No   Sun  Dinner    2  Dinner
9         14.78  3.23    Male     No   Sun  Dinner    2  Dinner
10        10.27  1.71    Male     No   Sun  Dinner    2  Dinner
11        35.26  5.00  Female     No   Sun  Dinner    4  Dinner
12        15.42  1.57    Male     No   Sun  Dinner    2  Dinner
13        18.43  3.00    Male     No   Sun  Dinner    4  Dinner
14        14.83  3.02  Female     No   Sun  Dinner    2  Dinner
15        21.58  3.92    Male     No   Sun  Dinner    2  Dinner
16        10.33  1.67  Female     No   Sun  Dinner    3  Dinner
17        16.29  3.71    Male     No   Sun  Dinner    3  Dinner
18        16.97  3.50  Female     No   Sun  Dinner    3  Dinner
19        20.65  3.35    Male     No   Sat  Dinner    3  Dinner
20        17.92  4.08    Male     No   Sat  Dinner    2  Dinner
21        20.29  2.75  Female     No   Sat  Dinner    2  Dinner
22        15.77  2.23  Female     No   Sat  Dinner    2  Dinner
23        39.42  7.58    Male     No   Sat  Dinner    4  Dinner
24        19.82  3.18    Male     No   Sat  Dinner    2  Dinner
25        17.81  2.34    Male     No   Sat  Dinner    4  Dinner
26        13.37  2.00    Male     No   Sat  Dinner    2  Dinner
27        12.69  2.00    Male     No   Sat  Dinner    2  Dinner
28        21.70  4.30    Male     No   Sat  Dinner    2  Dinner
29        19.65  3.00  Female     No   Sat  Dinner    2  Dinner
..          ...   ...     ...    ...   ...     ...  ...     ...
214       28.17  6.50  Female    Yes   Sat  Dinner    3  Dinner
215       12.90  1.10  Female    Yes   Sat  Dinner    2  Dinner
216       28.15  3.00    Male    Yes   Sat  Dinner    5  Dinner
217       11.59  1.50    Male    Yes   Sat  Dinner    2  Dinner
218        7.74  1.44    Male    Yes   Sat  Dinner    2  Dinner
219       30.14  3.09  Female    Yes   Sat  Dinner    4  Dinner
220       12.16  2.20    Male    Yes   Fri   Lunch    2   Lunch
221       13.42  3.48  Female    Yes   Fri   Lunch    2   Lunch
222        8.58  1.92    Male    Yes   Fri   Lunch    1   Lunch
223       15.98  3.00  Female     No   Fri   Lunch    3   Lunch
224       13.42  1.58    Male    Yes   Fri   Lunch    2   Lunch
225       16.27  2.50  Female    Yes   Fri   Lunch    2   Lunch
226       10.09  2.00  Female    Yes   Fri   Lunch    2   Lunch
227       20.45  3.00    Male     No   Sat  Dinner    4  Dinner
228       13.28  2.72    Male     No   Sat  Dinner    2  Dinner
229       22.12  2.88  Female    Yes   Sat  Dinner    2  Dinner
230       24.01  2.00    Male    Yes   Sat  Dinner    4  Dinner
231       15.69  3.00    Male    Yes   Sat  Dinner    3  Dinner
232       11.61  3.39    Male     No   Sat  Dinner    2  Dinner
233       10.77  1.47    Male     No   Sat  Dinner    2  Dinner
234       15.53  3.00    Male    Yes   Sat  Dinner    2  Dinner
235       10.07  1.25    Male     No   Sat  Dinner    2  Dinner
236       12.60  1.00    Male    Yes   Sat  Dinner    2  Dinner
237       32.83  1.17    Male    Yes   Sat  Dinner    2  Dinner
238       35.83  4.67  Female     No   Sat  Dinner    3  Dinner
239       29.03  5.92    Male     No   Sat  Dinner    3  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner    2  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner    2  Dinner
242       17.82  1.75    Male     No   Sat  Dinner    2  Dinner
243       18.78  3.00  Female     No  Thur  Dinner    2  Dinner

[244 rows x 8 columns]

In [134]:
tips.rename(index={0:'a'})

total_bill   tip     sex smoker   day    time size   time2
a         16.99  1.01  Female     No   Sun  Dinner    2  Dinner
1         10.34  1.66    Male     No   Sun  Dinner    3  Dinner
2         21.01  3.50    Male     No   Sun  Dinner    3  Dinner
3         23.68  3.31    Male     No   Sun  Dinner    2  Dinner
4         24.59  3.61  Female     No   Sun  Dinner    4  Dinner
5         25.29  4.71    Male     No   Sun  Dinner    4  Dinner
6          8.77  2.00    Male     No   Sun  Dinner    2  Dinner
7         26.88  3.12    Male     No   Sun  Dinner    4  Dinner
8         15.04  1.96    Male     No   Sun  Dinner    2  Dinner
9         14.78  3.23    Male     No   Sun  Dinner    2  Dinner
10        10.27  1.71    Male     No   Sun  Dinner    2  Dinner
11        35.26  5.00  Female     No   Sun  Dinner    4  Dinner
12        15.42  1.57    Male     No   Sun  Dinner    2  Dinner
13        18.43  3.00    Male     No   Sun  Dinner    4  Dinner
14        14.83  3.02  Female     No   Sun  Dinner    2  Dinner
15        21.58  3.92    Male     No   Sun  Dinner    2  Dinner
16        10.33  1.67  Female     No   Sun  Dinner    3  Dinner
17        16.29  3.71    Male     No   Sun  Dinner    3  Dinner
18        16.97  3.50  Female     No   Sun  Dinner    3  Dinner
19        20.65  3.35    Male     No   Sat  Dinner    3  Dinner
20        17.92  4.08    Male     No   Sat  Dinner    2  Dinner
21        20.29  2.75  Female     No   Sat  Dinner    2  Dinner
22        15.77  2.23  Female     No   Sat  Dinner    2  Dinner
23        39.42  7.58    Male     No   Sat  Dinner    4  Dinner
24        19.82  3.18    Male     No   Sat  Dinner    2  Dinner
25        17.81  2.34    Male     No   Sat  Dinner    4  Dinner
26        13.37  2.00    Male     No   Sat  Dinner    2  Dinner
27        12.69  2.00    Male     No   Sat  Dinner    2  Dinner
28        21.70  4.30    Male     No   Sat  Dinner    2  Dinner
29        19.65  3.00  Female     No   Sat  Dinner    2  Dinner
..          ...   ...     ...    ...   ...     ...  ...     ...
214       28.17  6.50  Female    Yes   Sat  Dinner    3  Dinner
215       12.90  1.10  Female    Yes   Sat  Dinner    2  Dinner
216       28.15  3.00    Male    Yes   Sat  Dinner    5  Dinner
217       11.59  1.50    Male    Yes   Sat  Dinner    2  Dinner
218        7.74  1.44    Male    Yes   Sat  Dinner    2  Dinner
219       30.14  3.09  Female    Yes   Sat  Dinner    4  Dinner
220       12.16  2.20    Male    Yes   Fri   Lunch    2   Lunch
221       13.42  3.48  Female    Yes   Fri   Lunch    2   Lunch
222        8.58  1.92    Male    Yes   Fri   Lunch    1   Lunch
223       15.98  3.00  Female     No   Fri   Lunch    3   Lunch
224       13.42  1.58    Male    Yes   Fri   Lunch    2   Lunch
225       16.27  2.50  Female    Yes   Fri   Lunch    2   Lunch
226       10.09  2.00  Female    Yes   Fri   Lunch    2   Lunch
227       20.45  3.00    Male     No   Sat  Dinner    4  Dinner
228       13.28  2.72    Male     No   Sat  Dinner    2  Dinner
229       22.12  2.88  Female    Yes   Sat  Dinner    2  Dinner
230       24.01  2.00    Male    Yes   Sat  Dinner    4  Dinner
231       15.69  3.00    Male    Yes   Sat  Dinner    3  Dinner
232       11.61  3.39    Male     No   Sat  Dinner    2  Dinner
233       10.77  1.47    Male     No   Sat  Dinner    2  Dinner
234       15.53  3.00    Male    Yes   Sat  Dinner    2  Dinner
235       10.07  1.25    Male     No   Sat  Dinner    2  Dinner
236       12.60  1.00    Male    Yes   Sat  Dinner    2  Dinner
237       32.83  1.17    Male    Yes   Sat  Dinner    2  Dinner
238       35.83  4.67  Female     No   Sat  Dinner    3  Dinner
239       29.03  5.92    Male     No   Sat  Dinner    3  Dinner
240       27.18  2.00  Female    Yes   Sat  Dinner    2  Dinner
241       22.67  2.00    Male    Yes   Sat  Dinner    2  Dinner
242       17.82  1.75    Male     No   Sat  Dinner    2  Dinner
243       18.78  3.00  Female     No  Thur  Dinner    2  Dinner

[244 rows x 8 columns]

In [142]:
tips['size'].map({2:'S' , 3:'s' , 4:'L',5:'l'})

0        S
1        s
2        s
3        S
4        L
5        L
6        S
7        L
8        S
9        S
10       S
11       L
12       S
13       L
14       S
15       S
16       s
17       s
18       s
19       s
20       S
21       S
22       S
23       L
24       S
25       L
26       S
27       S
28       S
29       S
      ... 
214      s
215      S
216      l
217      S
218      S
219      L
220      S
221      S
222    NaN
223      s
224      S
225      S
226      S
227      L
228      S
229      S
230      L
231      s
232      S
233      S
234      S
235      S
236      S
237      S
238      s
239      s
240      S
241      S
242      S
243      S
Name: size, Length: 244, dtype: object

In [145]:
tips['size'] = tips['size'].astype('str')

In [147]:
tips['size'].str.replace('2','s').replace('3','S')

0      s
1      S
2      S
3      s
4      4
5      4
6      s
7      4
8      s
9      s
10     s
11     4
12     s
13     4
14     s
15     s
16     S
17     S
18     S
19     S
20     s
21     s
22     s
23     4
24     s
25     4
26     s
27     s
28     s
29     s
      ..
214    S
215    s
216    5
217    s
218    s
219    4
220    s
221    s
222    1
223    S
224    s
225    s
226    s
227    4
228    s
229    s
230    4
231    S
232    s
233    s
234    s
235    s
236    s
237    s
238    S
239    S
240    s
241    s
242    s
243    s
Name: size, Length: 244, dtype: object

In [148]:
from sklearn.datasets import load_iris

In [149]:
data = load_iris

In [150]:
iris = pd.DataFrame(data.data, columns=data.feature_name)

AttributeError: 'function' object has no attribute 'data'