# 인공지능 

과거 - 인공지능을 if, then 문법을 사용했다.

    기계학습 - 사람의 지식을 사전에 모델링
    
기계학습 알고리즘 중 '뉴럴 네트워크' 대표적

레이어를 깊게 쌓을수록 해결을 못하는 것이 단점.

위의 문제를 해결하여, 많은 정보가 쌓여도 문제 없는 구조가 '딥러닝'


##### 기계학습, 딥러닝은 PTHON을 사용한다. 그 이유는?
->'NUMPY'

python은 하나의 실행속도는 느리지만, 여러개를 한번에 돌릴 경우에는 훨씬 더 빠르다.

matlab이 1순위였지만, numpy의 도입으로 이제는 python이 주된 프로그램으로 쓰인다.

NUMPY는 효율적인 코드 관리를 이끌어낸다.

사용하는 이유:
속도 빠르다. 사용하기 쉽다.

NUMPY는 모든 기반을 vector로 실행한다.

In [35]:
import numpy as np

0차(0차 array) scalar / 1차 vector / 2치 matrix / 3차원 벡터 : tensor

In [36]:
a=np.array(0)   #(array=?차원 데이터를 일컷는말.)

In [37]:
a  #결과에 array라고 나오면 NUMPY이다. <-매우 중요. 유념!

array(0)

In [38]:
type(a) #ndarray=닫혀있는array

numpy.ndarray

In [39]:
a=np.array([1,2])

In [40]:
a

array([1, 2])

In [41]:
a=np.array([[1,2],[3,4]]) #2차원 벡터   =>행렬과 똑같은 셈.

In [42]:
a

array([[1, 2],
       [3, 4]])

In [43]:
a=np.array([[[1,2],[3,4],[5,6]]])  #3차원

In [44]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [45]:
type(a)

numpy.ndarray

In [46]:
b=np.zeros([3,3])

In [47]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
c=np.eye(3)

In [49]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

1차원 벡터를 합쳐서 묶어주면 2차원 벡터가 된다.

In [27]:
c=np.eye(3)

In [28]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
c[0]

array([1., 0., 0.])

In [30]:
c[0][0]

1.0

In [51]:
a=np.array([[1,2],[3,4],[5,6]])

In [52]:
a.T

array([[1, 3, 5],
       [2, 4, 6]])

In [53]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

scipy는 numpy기반으로 정리가되어있다.

관련링크

https://scipy-lectures.org/intro/numpy/index.html

https://www.labri.fr

https://docs.scipy.org


# python이 너무 느려.. 해결책?

1. 좋은 하드웨어(GPU) 및 다른 컴퓨터언어사용
2. Compiler(컴파일러)사용
3. 효율적인 알고리즘을 짠다.


# NUMPY 생산  

In [54]:
import numpy as np # 순서1 : import 지정

In [56]:
np.__version__ # 버전체크

'1.16.2'

In [58]:
a = np.array([1,2,3,'4',5])  #array 설정 + 문자 넣어도됌! ex) '4'

In [60]:
a # homogenous  -> 값을 확인하지 않아도 되는 장점. //문자,숫자 둘다 같게 출력

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [61]:
b=[1,2,3,4,5]

In [63]:
a = np.array([1,2,3,4,5])

In [64]:
a+3

array([4, 5, 6, 7, 8])

In [65]:
a.dot(a)

55

In [66]:
a=[[1,2],[3,4]]

In [67]:
c=np.array(a)

In [68]:
np.sum(c, axis=1)

array([3, 7])

In [69]:
np.sum(c, axis=0)

array([4, 6])

In [70]:
a=np.arange(10)

In [71]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
%timeit np.sum(np.arange(10000000)) #이게 훨씬빠르다.

18.2 ms ± 217 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [80]:
%timeit np.sum(range(10000000))

1.16 s ± 20 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [81]:
type(a)

numpy.ndarray

In [82]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__