In [4]:
import numpy as np

In [15]:
a=[[1,2],[3,4]] #numpy도 숫자, 순서가 중요하다. 몇행 몇열 // 이런 것들은 sequence 타입
                #으로 만든다. 이것은 또 'indexing' or 'slicing'을 사용

In [6]:
c=np.array(a)

In [10]:
c.dtype  #크기

dtype('int32')

In [9]:
c.size  #원소의 개수

4

In [12]:
c.shape # 2행 2열로 만들어짐.

(2, 2)

In [14]:
c.ndim #dimension:2차원

2

In [8]:
np.sum(c,axis=0)

array([4, 6])

In [16]:
c=np.array(a)

In [17]:
c

array([[1, 2],
       [3, 4]])

In [19]:
c[0]  #array // arrange 를 이용해서 단순하게 만들어줄 수 있다.

array([1, 2])

In [20]:
x=np.ones((5,4))

In [21]:
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
x=np.full((5,4),9)

In [27]:
x

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [92]:
x=np.full(5,4)

In [93]:
x

array([4, 4, 4, 4, 4])

In [94]:
x=np.ones_like(a) #a의 shape과 동일하게 맞춘다.

In [95]:
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [96]:
x.strides #8로 나눈것

(20, 4)

stride   ->중요

In [97]:
x.astype('float')  #타입형태를 바꿔준다. 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
x.astype('float32')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [46]:
1/2

0.5

In [47]:
a=np.array([[1,2],[3,4]])

In [50]:
a[0][1]

1

In [48]:
a[0][1]=1.0

In [51]:
a.dtype

dtype('int32')

In [53]:
a[0][1]='a'  #해당되지 않는 요소는 error가 뜬다.

ValueError: invalid literal for int() with base 10: 'a'

In [54]:
a[0][1]=3

In [49]:
a

array([[1, 1],
       [3, 4]])

In [55]:
a=np.array([[1,2.],[3,4]])

In [57]:
a.dtype # 2 -> 2. 으로 바꿔주니 int->float

dtype('float64')

In [58]:
t=np.array([1,2],dtype='i1')

In [59]:
t

array([1, 2], dtype=int8)

--------

In [60]:
def x(a,b):
    return a+b

In [61]:
x([1,2,3],[4,5,6])

[1, 2, 3, 4, 5, 6]

In [62]:
def x(a,b):
    return [i+j for i,j in zip(a,b)]

In [64]:
x([1,2,3],[4,5,6])

[5, 7, 9]

In [65]:
@np.vectorize
def z(a,b):
    return a+b

In [67]:
z([1,2,3],[4,5,6]) #numpy는 벡터화도 쉽게 해준다.

array([5, 7, 9])

In [68]:
x=np.array([[1,2,3],[4,5,6]])

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
np.sum(x)

21

axis 개념을 숙지하자

In [77]:
a=np.arange(10).reshape(2,5) #2행 5열

In [78]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
a=np.arange(10).reshape(5,2) #5행 2열

In [80]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [89]:
a=np.arange(10).reshape(2,-1) # -1 : 보기 편하게 나열하라.

In [90]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
np.mean(a,axis=1)

array([2., 7.])

In [100]:
np.mean(a,axis=0)

array([2.5, 3.5, 4.5, 5.5, 6.5])